syslog_paths:
  - "E:/SolarWinds/Logs/vWLC_PoC-AI1_20260415130741565.log"
  - "E:/SolarWinds/Logs/Switches_20260415130333082.log"
  - "E:/SolarWinds/Logs/merged.log"

ap_switch_map: "site_mapping.csv"

#openai_api_key: "YOUR_OPENAI_API_KEY"

time_window_minutes: 15

#zabbix:
#  send_to_zabbix: false
#  host: "AI-Correlation"
#  server: "127.0.0.1"
#  key: "ai.incident"
``
